import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "./theme-config.css";
import { UserProvider } from "@/context/UserContext";

const vazir = Vazirmatn({
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "Tsco DKP Analyzer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>
        <Theme appearance="light" accentColor="crimson" grayColor="mauve">
          <UserProvider>{children}</UserProvider>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
